target/lorri

direnv/nixos.nix

Fish does not support `$(...)` command substitution at the moment.

direnv: fix fish init

---

default.nix
example/shell.nix
nix/nixpkgs.nix

We only need to enable the Overlay for rust nightly, which we only use
in our dev-shell for lorri. In all other places we don’t need it.
Having no default value also broke the tutorial (direnv setup),
because `nix-env -f ./nix/nixpkgs.nix` would not work anymore.

nix/nixpkgs.nix: default `enableMozillaOverlay` to `false`.

---

src/ops/direnv/mod.rs

Closes #9, though we should make a new issue to have it auto-evaluate the first time.

direnv: print error if lorri watch has not been run

---

.envrc
.gitignore
shell.nix

*This PR was missed in the migration, already merged in the original repository*
This is the first work on integrating cargo plugins.
It mostly sets CARGO_INSTALL_ROOT to the project directory, so cargo install <plugin> will be put in ./.cargo/bin, which is also added to the direnv PATH.

Cargo plugins

---

src/build_loop.rs
src/ops/shell.rs
src/ops/watch.rs

As part of researching, experimenting with, and testing for bug #23, I've made some improvements to BuildLoop. Definitely go commit-by-commit, but the end result means BuildLoop is much more ergonomic:
- you don't have to use a mpsc channel to use BuildLoop
- you don't have to use a thread to use BuildLoop
an OK(...) from `once()` means it worked fine, and an Err means it didn't (before we could return a `Ok(Failure(...))` which is pretty weird
and finally:
- `lorri shell`'s code is nicer, since we don't need to wait for just the first message from the RX
- exiting the shell inside `lorri shell` actually exits

Improve build loop

---

shell.nix

racer uses it for showing documentation and jump-to-definition.

shell.nix: Set RUST_SRC_PATH

---

README.md

I got stuck on direnv magically not seeming to do anything after setting everything up. It took me a while to realize that I missed the "enable direnv according to its instructions" step (assuming that the Nix expression would do that for me), as it was a relatively unnoticeable footnote.
This PR changes that, by making enabling it a clear and discrete step in the setup process.

Make 'enable direnv' step more obvious

---

src/cli.rs
src/main.rs
src/ops/init/mod.rs
src/ops/mod.rs

Implements an `init` command that writes a default shell.nix and .envrc to $CWD if those files don't exist already.
Should fix #41 (?) however it does nothing about validating whether or not the existing `shell.nix` is valid - which is something @Profpatsch mentioned in #41

Implement "init" command

---

src/builder.rs

Moves to `--argstr`, because otherwise nix interprets a path like
`/foo/my project/` as a function call and aborts.
Fixes: https://github.com/target/lorri/issues/76

builder.rs: all spaces in the lorri src directory

---

.travis.yml
.travis.yml.nix
.travis_fold.sh
shell.nix

Add caching to the travis (non-nix-build) jobs.
Before: 
After:
Now both runs spend most of their time in fetching the nightly rust toolchain and the MacOS builder spends another 2 minutes or so setting up a multi-user nix daemon when a single-user install would suffice.
The `nix-build` runs could also be sped up by passing the cargo cache manually to the build.

Travis cargo cache

---

nix/bogus-nixpkgs/stdenv/setup
release.nix
src/logged-evaluation.nix
src/ops/direnv/envrc.bash
tests/integration/bug23_gopath/shell.nix
tests/integration/bug23_setuphook.rs
tests/integration/bug23_setuphook/shell.nix
tests/integration/direnvtestcase.rs
tests/integration/envrc.rs
tests/integration/main.rs

#75 implemented support for shellHooks, but ... oops: Go doesn't use shellHooks to setup GOPATH.
This code monkeypatches much sooner: https://github.com/NixOS/nixpkgs/blob/22a765d0da7070311e5b8c2bb29fa496c833dae5/pkgs/stdenv/generic/setup.sh#L238-L284
and correctly supports GOPATH.
It also fixes a bit of an annoying bug where an appended variable would be appended, including a delimiter, even if the variable was empty before: https://github.com/target/lorri/commit/664727ad8159557362cf5c5359030009d4cf0aa7
cc @mmlb who found and helped debug this problem. (and tested it fixed it!)

Actually support Go

---

default.nix

Using `builtins.fetchGit` has multiple problems, it makes nix cache
for some time (1 hour?) which means changes to the source directory
are (silently) ignored.
It also requires a `.git` dir to exist, which is not the case for
distribution archives, and thus breaks `nix-env` on our rolling
release branch.
Closes: https://github.com/target/lorri/issues/92
You can test it with `nix-env -if https://github.com/target/lorri/archive/default.nix-use-nix-gitignore.tar.gz` cc @PierreR

default.nix: Use nix-gitignore instead of fetchGit to filter src

---

release.nix

Afterwards, we need to push the `rolling-release` branch to master.

Update changelog for release

---

src/build_loop.rs
src/builder.rs
src/lib.rs
src/nix.rs
src/osstrlines.rs

Split out from https://github.com/target/lorri/pull/117
Before, the nix output was parsed into `str`/`String` before parsing
it into lines (which is the behavior of the various `.lines()`
methods).
We can, however, not assume that nix output is valid UTF-8. Take for
example the following derivation:
```
with import <nixpkgs> {};
runCommand "foo" {} ''
dd if=/dev/urandom of=./foo bs=1M count=1
cat ./foo
touch $out
''
```
which prints 1 megabyte of random output to stdout (and thus to nix’s
`stderr`). This random data is not valid UTF-8, which means lorri is
going to choke on the derivation output and crash with a decoding
error.
Instead, we keep the output a `Vec<u8>`, convert it to an
`OsString` (which is a wrapper around `Vec<u8>` on POSIX systems) and
split on `\n` (which is the line …

nix, builder: Fix nix output parsing

---

src/cli.rs
src/locate_file.rs
src/main.rs

use --shell-file or -s option to declare the nix file to use when
running command info, watch, direnv
refs #116
:warning:  first time I contribute to a rust project.
thank you for this great project, it saves me a lot of time
thank you for marking this as good first issue

feat: add option to define the shell.nix location

---

src/ops/daemon.rs

This PR simply adds a little `lorri: ready` output when starting the daemon.
Fixes #142

daemon: print message on start-up

---

.travis.yml
.travis.yml.nix

The `.travis.yml.nix` was diffing `.travis.yml` under the `carnix-idempotent` travis step, this is probably a typo and should be `Cargo.nix`.

Fixed a Typo in the Travis cfg

---

script-tests/run-all.sh
shell.nix

If we add new phases, we need to add them to the final status code
check as well, otherwise CI doesn’t fail if a phase fails.
Broken out of #117.

CI: fix the ci_check return code accumulation

---

src/lib.rs
src/ops/daemon.rs
src/thread.rs

Alternate implementation to #148 
This implementation handles any panic in the spawned threads, and doesn't require explicitly returning a specific unrecoverable error type.
Also, it gets rid of a few todo's in the daemon.

daemon: panic if any threads panic

---

src/ops/direnv/envrc.bash
src/ops/direnv/mod.rs

Fix #151
Fix #113 
1. Print a more correct warning to the user if the environment is not cached, or if the lorri daemon is not updated.
2. Simplify handling when the daemon isn't running by watching the socket, so we evaluate when the daemon starts.

Bug 151/start lorri daemon

---

src/ops/direnv/envrc.bash

These bash variables probably shouldn't be propagated.
Fixes #153 cc @roberth

envrc: punt on OLDPWD,PWD,SHELL

---

nix/nixpkgs.nix

We can easily replace it by builtins, so we don’t need a `NIX_PATH`
set up to reference our nixpkgs pin. This is helpful for sandboxed
execution.

nix/nixpkgs.nix: remove `hostpkgs`

---

src/logged-evaluation.nix
src/ops/direnv/envrc.bash

Sets IN_NIX_SHELL environment variable to `impure` instead of 1.
I think this should resolve https://github.com/target/lorri/issues/140 as I couldn't see any other references to IN_NIX_SHELL, but I should probably add a test as well? I checked it manually by checking the value of the environment variable with direnv/lorri in the development shell for this project.

Set IN_NIX_SHELL to impure (#140)

---

src/cli.rs
src/main.rs
src/ops/watch.rs

Adds a `--once` argument to lorri watch, to only run one evaluation.
`lorri install` was proposed instead, but we don’t want it to sound
like the command changes the system of the user (think `make
install`).
Ultimately, `lorri watch` is going to be replaced by `lorri daemon`
completely, then we should introduce a `lorri run` command which does
the same as `lorri watch --once`.
Co-Authored-By: Graham Christensen <graham@grahamc.com>
Co-Authored-By: Tobias Pflug <tobias.pflug@tweag.io>

add `lorri watch --once`

---

src/builder.rs

Finally solves the issue of watching way too many files. See commit messages for details.
<s>
Merge #117 first!
Edit: the utf8-test will break, because it’s still broken on #117.
</s>
Is now based on `master`.

Builder default.nix logic

---

.gitignore
.travis.yml
.travis.yml.nix

It seems like Travis is withholding the Cachix signing key from PRs from forks (which is appropriate.)
This PR prevents `cachix push` if the signing key isn't available.

Gating `cachix push` on availablility of signing key

---

nix/bogus-nixpkgs/default.nix
src/nix.rs

Callers can pass a `Sender<OsString>` to CallOpts. Each line of stderr
outpuut from Nix is passed over this channel.

nix.rs: allow reading stderr output via Rx/Tx

---

.travis.yml
.travis.yml.nix

The older version of Nix on darwin (2.0) had a bug where it wouldn't
interpret a symlink as a `.drv`.
The upstream Travis support for newer Nixes on Darwin is a bit broken,
so this is working around that for now.
The default language changes to `minimal`, but the Linux version
overrides it to `nix`.

(against #117) nix: test on 2.3.1

---

nix/nixpkgs.json

The current pinned snapshot is five months old. Updating it means fewer things need to be downloaded initially.

Pin nixpkgs to current NixOS 19.09 snapshot

---

Cargo.lock
Cargo.nix
Cargo.toml
default.nix
nix/carnix/crates-io.nix
shell.nix
src/main.rs

Add human-panic crate which provides a handler for catching panics and
providing a more human friendly message including contact information
and where to submit bugs as directed by Cargo.toml.
Current provided as pinned to a git commit pending a 2.0 release of
human-panic.
NOTE: In order to get the panic message to appear the binary must both
be a release target and the RUST_BACKTRACE environment variable must be
unset for it to appear. Setting RUST_BACKTRACE to 0 or similar will give
you a regular panic without a backtrace but will not display this
message.
Example panic output from panicking immediately after setup:
```
Well, this is embarrassing.
lorri had a problem and crashed. To help us diagnose the problem you can send us a crash report.
We have generated a report file at …
```

Add human-panic

---

src/build_loop.rs
src/socket/communicate.rs
src/watch.rs
tests/daemon/main.rs

This addresses #49 - The watch module gets a `Reason` type, and reports `FilesChanged(path, count)`. This could certainly be iterated on for friendliness, but right now it's a step up from just `Started`.

Report cause of build

---

src/constants.rs
src/ops/mod.rs

what it says on the tin. Good error messages if something in the user environment is not right.

constants/Paths: Split IO errors into enum for easier debugging

---

src/main.rs
src/ops/daemon.rs
src/ops/direnv/mod.rs
src/ops/info.rs
src/ops/init.rs
src/ops/mod.rs
src/ops/ping.rs
src/ops/upgrade/mod.rs
src/ops/watch.rs

This consolidates the `ExitError` type and makes lorri output different error codes depending on which kind of error happened.
Inspired by https://github.com/target/lorri/pull/184, but doesn’t use the code because it takes a slightly different approach.

Exit error consolidation

---

.travis.yml
.travis.yml.nix
shell.nix

This improves caching in situations where the checks fail (because dependencies are already uploaded to cachix before the checks, which should reduce the turnaround time for PRs, esp. for darwin, considerably.

Ci run cachix even on failing checks

---

contrib/README.md
contrib/lorri.service
contrib/lorri.socket

**[`lorri`, including a user service definition, is now in `nixpkgs`](https://github.com/NixOS/nixpkgs/pull/72889) :tada:**
---
Addresses some of #96. `lorri.socket`, `lorri.service` and `lorri.nix` are mostly taken from comments on that issue.
[`contrib/README.md` preview](https://github.com/curiousleo/lorri/blob/contrib/contrib/README.md).

Run lorri daemon as a service on Linux and macOS

---

Cargo.lock
Cargo.nix
nix/carnix/crates-io.nix
src/nix.rs

Update deps (`cargo update; ./nix/update-carnix.sh`) and get rid of one deprecation warning (`Vec1::from_vec` -> `Vec1::try_from_vec`).

cargo update

---

README.md

This is now handled correctly:
https://github.com/target/lorri/blob/9418645479149b48da4a356cbefe9e724ec963ff/src/builder.rs#L160-L170

Remove "default.nix" trick

---

src/main.rs

In #250, `nix-instantiate` claims to be unable to find the `nixpkgs` path passed to it. This PR adds assertions to make sure the relevant directory and file do in fact exist. With this PR, it should be very obvious if due to some CI environment setup mistake we have made the `nixpkgs` path unavailable to the test itself.

Add sanity checks to investigate #250

---

default.nix
nix/bogus-nixpkgs/default.nix
nix/fmt.sh
nix/nixpkgs.nix
nix/runtime.nix
shell.nix
src/builder.rs
src/daemon/rpc.rs
src/lib.rs
src/logged-evaluation.nix
src/main.rs
src/ops/direnv/mod.rs
src/ops/info.rs
src/ops/ping.rs
src/ops/upgrade/upgrade.nix
src/project.rs
src/trivial-shell.nix
tests/integration/direnvtestcase.rs

**Motivation:** we want to be able to generate a `services.json` file based on a nix file. This `services.json` is meant to be consumed by the `lorri services` client to start and stop development services.
On the Nix side, this makes both `shellSrc` and `servicesSrc` optional; at least one of them must be provided.
On the Rust side, `NixFile` is now an enum with possible values `NixFile::Shell(PathBuf)` and `NixFile::Services(PathBuf)`.
**Todo**

Generate services.json

---

src/watch.rs

We ignore metadata modificaiton events for the profiles directory
tree as it is a symlink forest that is used to keep track of
channels and nix will unconditionally update the metadata of each
link in this forest.
These ModifyKind::Metadata events are spurious and they can easily
cause a rebuild-loop when the shell.nix files  does not pin it's
version of nixpkgs or other channels.
When a Nix channel is updated we will recieve a data modification
event, so ignoring these metadata modifications will not impact
lorri's ability to correctly watch for changes.
Fixes #176

Ignore some metadata modificaiton events

---

.travis.yml
.travis.yml.nix
nix/fmt.sh
shell.nix

Partial workaround for https://github.com/target/lorri/issues/258.
Cachix does not work on macOS (https://github.com/cachix/cachix/issues/228) and Hydra does not successfully build `clippy` (https://github.com/NixOS/nixpkgs/pull/77327, https://github.com/NixOS/nixpkgs/issues/77358). As a result, in order to run `clippy`, we build it from scratch on every CI run on macOS. This adds about 20 minutes of build time.
There is no need to run `clippy` both on macOS and on Linux. So to circumvent this issue, this PR changes the CI setup slightly so that lints (including `clippy`) are only run on Linux.

No clippy on macOS CI

---

shell.nix

`lorri shell` does not exist, so the `newlorri` alias does not work.

shell.nix: remove unsupported "newlorri" alias

---

default.nix

See https://github.com/NixOS/nixpkgs/pull/77380#discussion_r364849796 and https://github.com/NixOS/nixpkgs/commit/c976dc165b69c30f54d8fd42ec541285c598a345#diff-cf738915a62799c87e7c6834f40c3fcd
`nix`, `which` and `direnv` are required for testing and for the successful execution of the daemon, but they are not build inputs for lorri.

Remove direnv, which from buildInputs

---

src/cli.rs
src/logging.rs
src/main.rs
src/ops/info.rs

The `info` command currently shows only information that is accessible via other means too. Let's make it more useful!
In this PR:
- every log line: remove "version" field
- every log line: change field name of the shell nix "root" to "expr"
- info command: keep printing lorri version
- info command: include information about GC roots

info command: show gc roots

---

Cargo.lock
Cargo.nix
Cargo.toml

Fixes https://github.com/target/lorri/issues/216.
Bumps `human-panic` to a version including this fix: https://github.com/rust-cli/human-panic/pull/66.

human-panic: Include cause on Rust stable

---

release.nix
shell.nix
src/cli.rs
src/main.rs
src/ops/mod.rs
src/ops/shell.rs
tests/shell/loads_env/shell.nix
tests/shell/main.rs

Resurrects `lorri shell`. The idea is to make it as easy as possible for people with existing projects with `shell.nix` files to get started with lorri. The pitch is "just use `lorri shell` instead of `nix-shell`".
This version of `lorri shell` does not cache build results and does not attempt to launch from the cache. That will be done in a follow-up PR.

lorri shell

---

Cargo.lock
Cargo.nix
Cargo.toml
nix/carnix/crates-io.nix

We don't use `bincode` anymore.

Remove bincode dependency

---

src/cli.rs
src/main.rs
src/ops/mod.rs
src/ops/shell.rs
src/ops/start_user_shell.rs
tests/shell/main.rs

Addresses part 2 of https://github.com/target/lorri/issues/297.
Prepends `(lorri) ` to the PS1 if the user uses bash as their shell.
```console
[leo@daphnis project]$ basename $SHELL
bash
[leo@daphnis project]$ lorri shell
lorri: building environment...... done
(lorri) [leo@daphnis project]$
```
The PR also introduces the structure required to perform customisations for other shells.

lorri shell: set PS1 in bash

---

src/build_loop.rs
src/builder.rs
src/error.rs
src/lib.rs
src/nix.rs
src/ops/shell.rs
src/ops/watch.rs
src/project/roots.rs
tests/integration/direnvtestcase.rs

Addresses https://github.com/target/lorri/pull/295#issuecomment-577966057: `builder::run` now returns a `BuildError` which contains the logs that caused the build to fail instead of just `FailedAtInstantiation` ([diff here](https://github.com/target/lorri/pull/296/files#diff-058d40ebe40b5d40f6ffb05cf3d82dd8R215)), making it possible to present that information to the user.
**Before:**
```console
$ lorri shell
lorri: building environment. done
Jan 27 11:28:13.915 ERRO build failed: FailedAtInstantiation
```
**After:**
```console
$ lorri shell
lorri: building environment.. done
Jan 27 11:31:49.069 ERRO build failed: Nix process returned with exit code 1. Error logs:
error: syntax error, unexpected ',', expecting $end, at /home/leo/Code/lorri/shell.nix:6:1
```
Simplifies internal error …

Show Nix failure logs to user

---

src/builder.rs
src/error.rs
src/nix.rs

Follow-up to https://github.com/target/lorri/pull/296.
- Include commands in error messages if possible. This helps with debugging.
- `BuildError` variants are now represented as structs with per-field documentation.
Example (when combined with #303):
<pre>lorri: building environment.. done
Jan 28 16:20:23.397 <font color="#CC0000">ERRO</font> <b>Build failed. No cached environment available.</b>
<b>Build error: Nix process returned exit code 1.</b>
<b>$ &quot;nix-instantiate&quot; &quot;-vv&quot; &quot;--add-root&quot; &quot;/tmp/.tmpzX7Qhq/result&quot; &quot;--indirect&quot; &quot;--argstr&quot; &quot;runtimeClosure&quot; &quot;/nix/store/ymb5ivx2yadbaflw38985xy156059kdy-runtime-closure.nix&quot; &quot;--argstr&quot; &quot;shellSrc&quot; &quot;/home/leo/Code/shell.nix&quot; …

Include commands in error messages where possible

---

src/cli.rs
src/main.rs
src/ops/shell.rs
tests/shell/main.rs

Addresses part 4 of https://github.com/target/lorri/issues/297. 
> Allow a user to open a cached lorri shell with no evaluation or build with `--cached`. If `lorri shell` fails (or takes a "long time"), suggest this option automatically. If the user runs with `--cached` without a cached evaluation, it should exit non-zero.
Todo:

lorri shell --cached

---

src/ops/start_user_shell.rs

Prepend `(lorri) ` to the user's PS1 if they use zsh.

lorri shell: set PS1 if user shell is zsh

---

README.md

Relates to https://github.com/target/lorri/issues/269.
Users might reasonably expect that lorri, being a Rust command line tool, can be obtained from https://crates.io. It cannot, for good reasons, which we should spell out.

Explain why lorri is not on crates.io

---

nix/nixpkgs-fmt.nix
nix/nixpkgs.json
nix/nixpkgs.nix
nix/update-dependencies.sh
src/build_loop.rs
src/ops/watch.rs
tests/integration/envrctestcase.rs

Relates to https://github.com/target/lorri/pull/314#issuecomment-580258799.
If we want to support NixOS 19.09, we should pin a version of it rather than of `nixos-unstable`.

Pin nixos-19.09 instead of nixos-unstable

---

MAINTAINERS.md
release.nix
src/cli.rs
src/daemon.rs
src/ops/shell.rs

Just a little cleanup before we go to 1.0.
See https://github.com/target/lorri/pull/317/commits/84fa27579ef79c1ec3e04b4ba42ac229a7c5422d commit message.

Subcommands cleanup

---

.gitattributes

This PR will mark `Cargo.nix` file as generated in order to fix a little bit skewed language statistics of `lorri`'s GitHub repository.

Add .gitattributes with Cargo.nix as generated

---

.travis.yml
.travis.yml.nix

Fix a few CI linting errors and enable master builds.
I’m not 100% sure whether this disables PR builds, let’s see …

Ci build on master

---

release.nix
src/trivial-shell.nix

The default template is missing one useful feature that would allow users to evaluate their shells with modified packages set. The approach to fixing this is to update the default template to take `pkgs` attrset via a function argument.

make nixpkgs overridable in the shell.nix template

---

release.nix
src/ops/direnv/envrc.bash
tests/integration/envrc.rs

Closes #18.
Quoting the value of variable in the prepend function prevents `eval` from treating everything after a space as another command to evaluate.
```
❯ echo $PATH
/Users/blades/.nix-profile/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin
❯ lorri shell
lorri: building environment......... done
/Users/blades/Library/Caches/com.github.target.lorri.lorri.lorri/cas/fe2381e5f5b538e916a10973b0a6dea1: line 61: Fusion.app/Contents/Public:/Library/TeX/texbin: No such file or directory
❯ ./target/debug/lorri shell
lorri: building environment......... done
```
~- [ ] Updated the documentation (code documentation, command help, ...)~

safely handle spaces in PATH

---

MAINTAINERS.md
release.nix
src/cli.rs
src/daemon.rs
src/main.rs
src/ops/shell.rs
tests/shell/main.rs

Put each internal commands in a subcommands visible for all users.
close #343 
BTW should I remove the ping command ? (related to the TODO comment in file)

fix(cli): display internal commands in a subcommand #343

---

src/build_loop.rs
src/watch.rs

The refactor I mentioned in https://github.com/target/lorri/pull/355#issuecomment-602318309
Splits the recursive enumeration of files from the actual adding to the watcher.
cc @hamishmack @curiousleo

Watch refactor path adding logic

---

release.nix
src/cli.rs
src/ops/shell.rs

Either we do `-` or `_`, and we already use `-` for all flags and
`self-upgrade`. Consistency is king for good UX.
This is obviously a breaking change, but these are `internal` and haven’t seen an official release so far (plus we added the `internal`-as-a-subcommand thing recently anyway).
cc @curiousleo @nyarly

ops: banish underscores in cli commands

---

README.md

Direnv isn't and shouldn't be automatially installed on installing lorri, per https://github.com/NixOS/nixpkgs/pull/85144

Fix README (direnv shouldn't be auto-installed)

---

src/trivial-shell.nix

For bash users, `mkShell` overrides their path with a non-interactive
shell, which breaks their shells.
Adding `bashInteractive` is a workaround, so we should recommend that
and add it via `lorri init`.
Closes https://github.com/target/lorri/issues/383
cc @deliciouslytyped

src/trivial-shell.nix: add bashInteractive

---

src/ops/direnv/mod.rs

If I see an error message, I expect the process to crash immediately
after. So let’s make this a warning.

(trivial) ops/direnv/mod.rs: daemon not running error->warn

---

release.nix
src/build_loop.rs
src/builder.rs
src/cli.rs
src/daemon.rs
src/main.rs
src/nix.rs
src/nix/options.rs
src/ops/daemon.rs
src/ops/shell.rs
src/ops/watch.rs
tests/daemon/main.rs
tests/integration/direnvtestcase.rs
tests/shell/main.rs

Adds the ability to input additional nix arguments through to the nix
commands. For our sanity and so that we don’t have to replicate the
whole nix API, they are passed as json string on the command line.
However, I don’t know how an exhaustive API would look like (nix has a
lot of configuration options and their semantics is pretty weird in
places), so I opted to only add `--substituters` and `--builders`. We
even gain a nicer interface by using an optional list.
I’m not yet positive on how to document the JSON interface more
nicely, maybe we do want to expose all options as command line flags,
but I really don’t know how that would look without leading to a mess.
The changes are rather simple and mostly mechanical.
As a followup, we should add the same flag to `watch` and `shell`.
cc …

daemon: Make it possible to pass `substituters` and `builders`

---

.github/workflows/ci.yml
.travis.yml.nix
default.nix
nix/nixpkgs-1909.json
nix/nixpkgs-1909.nix
nix/nixpkgs-stable.json
nix/nixpkgs-stable.nix
nix/nixpkgs.json
nix/overlay.nix
nix/update-dependencies.sh
shell.nix

There are a few steps I've taken to make this as robust as possible:
0) Add a `nixpkgs` arg to default.nix and shell.nix, allowing us to more
easily specify which nixpkgs to use -- rather than having to use
`nix-build --arg pkgs 'import ./nix/nixpkgs-1909.nix'`, one only needs
to run `nix-build --arg nixpkgs ./nix/nixpkgs-1909.nix`.
1) Create two separate nixpkgs expressions, nixpkgs-stable and
nixpkgs-1909. This allows us to build against NixOS 19.09 by running the
aforementioned `nix-build --arg nixpkgs ./nix/nixpkgs-1909.nix`
commandline. (Also add nixos-19.09 to the update-dependencies script.)
2) Add an `overlay` build step that overlays the lorri available from
the current stable nixpkgs, to ensure that it is still possible to do
so. ("in order to not have to wait on a new lorri …

ci: ensure compatibility with 19.09

---

.github/workflows/ci.yml
src/watch.rs

Avoids failures like in https://github.com/target/lorri/runs/780067510.
CI machines are terribly slow sometimes. This should make timeout based tests less flaky.

Increase test watcher timeout to 1s

---

.github/workflows/ci.yml
src/main.rs

Increases coverage of GH actions CI.
To debug CI issues, it was useful to introduce an environment variable to disable the installation of the `human_panic` panic handler, based on https://github.com/target/lorri/pull/430#issuecomment-648317335.

Test `lorri self-upgrade local` in GitHub action

---

CONTRIBUTING.md

This idea was stolen from the tvl depot:
https://code.tvl.fyi/tree/docs/CONTRIBUTING.md#n35
Followup to the idea in https://github.com/target/lorri/pull/436#issuecomment-649299362

doc(CONTRIBUTING.md): describe commit message scheme

---

src/daemon.rs
src/daemon/rpc.rs
src/lib.rs
src/nix.rs
src/ops/daemon.rs
src/ops/shell.rs
src/project.rs
src/socket.rs
src/thread.rs
tests/daemon/main.rs
tests/shell/main.rs

This is a rather bigger change than I hoped it would be, but I think I found a good solution for the issues many people have been having in https://github.com/target/lorri/issues/375.
Which is mainly that the thread pool was not re-throwing the call stack of the panicking inner thread, but just throwing its own panic, so `human-panic` would show the same error message for every panic (that the `dyn Any` returned by `thread_handle.join()` cannot print the actual data did not help).
I did a bit of refactoring before tackling the actual problem and wrote quite extensive commit messages, so best reviewed commit-by-commit.
I started using [commit markers](https://code.tvl.fyi/tree/docs/CONTRIBUTING.md#n35) to better distinguish refactor commits from actual feature commits, and it looks quite …

Thread.rs correctly unwind call stacks

---

.github/workflows/ci.yml

Followup to https://github.com/target/lorri/pull/436#issuecomment-651221145.
Next, I'd like to set up clippy and rustfmt to run on PRs. This would only happen on `ubuntu-latest`, because apparently, darwin can sometimes ship without `clippy`/`rustfmt` (see the failed CI on https://github.com/cole-h/lorri/pull/4 for examples of what happens when you try)?
cc @curiousleo

chore(ci): run on darwin too

---

src/ops/direnv/mod.rs

We were throwing every single error that could be thrown by a varlink
connection into a single bin, even though only one trivial case would
mean the socket is not reachable.

ops/direnv: don’t ignore every connection error

---

Cargo.lock
Cargo.nix
Cargo.toml
MAINTAINERS.md
release.nix

I’d like to push the manpage change to nixpkgs.
The MAINTAINERS says we don’t use the patch version field, but I don’t think it’s wise to bump the minor version for an update in documentation, so I’d use the patch field in this case.

release 1.1.1

---

.github/workflows/ci.yml

Github actions is super unoptimized, so if you push a branch to the
repo and then create a PR for it, it won’t recognize that it is
building exactly the same commit and schedule the whole matrix again.
Since there is a restriction on how many builders we can
use (especially BSD light builders), this increases our CI build time
considerably.
So let’s restrict to master.
Based on the reply in
https://twitter.com/basile_henry/status/1288724098319814657

fix(ci): only run CI on push to master

---

.github/workflows/ci.nix
.github/workflows/ci.yml
default.nix
shell.nix

This revives the code we used for the travis config, which enabled us
to deduplicate the uncomfortably large amount of CI config. :)
It starts out by converting the config to nix, then refactoring until the gist of the jobs was readable again.
Then it removes some of the build steps, to bring down evaluation time.
Also updates the rust cache action.
cc @cole-h

CI: dedup and trim

---

Cargo.lock
Cargo.nix
Cargo.toml
nix/carnix/crates-io.nix
release.nix
src/main.rs

Make the `lorri daemon` subcommand exit with 0 on SIGINT
or SIGTERM.
Other `lorri` subcommands preserve the default SIGINT
and SIGTERM behaviors.
This change is done adds the [ctrlc](https://github.com/Detegr/rust-ctrlc)
crate, by Antti Keränen, as a dependency. This crate provides a simple
and safe interface for handling SIGINT and SIGTERM.
An alternative to the `ctrlc` crate would be to implement the response to the signals
using the the `nix` crate, which is already a lorri dependency.
The downside of this would be adding `unsafe` code to the codebase.
Closes #463 .
* added the ctrlc crate as a dependency
* added a function that exits with 0 for SIGINT or SIGTERM
* call that function on the Daemon arm of the match statement in `run_command()`

feat(sigterm): daemon exits with 0 on SIGINT or SIGTERM

---

README.md

Addresses macOS-specific concerns within #96.
This PR documents how `lorri` may be installed and maintained as a system service using `nix-darwin`, in a similar manner to how it's managed with NixOS or home-manager on Linux.

Adds nix-darwin instructions to the README
